import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Inputs from '../componets/Inputs';
import styles from '../styles/Home.module.scss';
import Map from '../componets/Map';
import Script from 'next/script';
import { useEffect, useState } from 'react';
import ErrorBoundary from '../componets/ErrorBoundries';

const Home: NextPage = () => {
  const [selected, setSelected] = useState('');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [fromLocation, setFromLocation] = useState({});
  const [toLocation, setToLocation] = useState({});
  const [distance, setDistance] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!!fromLocation && !!toLocation) {
      const services = new google.maps.DistanceMatrixService();
      services.getDistanceMatrix(
        {
          origins: [fromLocation, from],
          destinations: [toLocation, to],
          travelMode: google.maps.TravelMode.DRIVING,
        },
        (result: any, status: any) => {
          if (status === google.maps.DirectionsStatus.OK) {
            setDistance(result);
          } else {
            setError(result);
          }
        }
      );
    }
  }, [fromLocation, toLocation, from, to]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ErrorBoundary>
        <div className={styles.split}>
          <Inputs
            selected={selected}
            setSelected={setSelected}
            from={from}
            setFrom={setFrom}
            to={to}
            setTo={setTo}
            fromLocation={fromLocation}
            toLocation={toLocation}
            setFromLocation={setFromLocation}
            setToLocation={setToLocation}
            distance={distance}
          />
          <Map fromLocation={fromLocation} toLocation={toLocation} />
        </div>

        <Script
          src='https://maps.googleapis.com/maps/api/js?key=AIzaSyB4PYjvrGpT3dlTXb3BQY3JhLslRngDWHU&v=3.exp&libraries=geometry,drawing,places'
          strategy='beforeInteractive'
        />
      </ErrorBoundary>
    </div>
  );
};

export default Home;
